version: 6.1.0.{build}

os: Windows Server 2012

environment:
  Major: 6
  Minor: 1
  Revision: 0

services:
  - mssql2012sp1

install:

build:
  project: Master.proj
  verbosity: normal
  
test: off
before_test:
- sqlcmd -S "(local)\SQL2014" -E -i "%APPVEYOR_BUILD_FOLDER%\Database\SqlServer\Tracker.sql"

artifacts:
- path: Build\*.nupkg