version: 6.1.0.{build}

os: Windows Server 2012

environment:
  Major: 6
  Minor: 1
  Revision: 0
  SqlPass:
    secure: 0gZDzNpTgeoXGnBaTbkpeg==
    
services:
  - mssql2014
  
install:
  - cmd: sqlcmd -S "(local)\SQL2014" -U sa -P %SqlPass% -i "%APPVEYOR_BUILD_FOLDER%\Database\SqlServer\Tracker.sql"

build:
  project: Master.proj
  verbosity: normal
  
test: off

artifacts:
  - path: Build\*.nupkg